# Generated by Django 5.0.4 on 2024-04-12 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuarioID', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('rol', models.CharField(choices=[('usuario', 'Usuario normal'), ('admin', 'Administrador')], default='usuario', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPeso',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pesousuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFitnes.usuarios')),
            ],
            options={
                'ordering': ['-ID'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicios',
            fields=[
                ('ejercicioID', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('repeticiones', models.IntegerField()),
                ('gasto_energetico', models.IntegerField()),
                ('usuario', models.ManyToManyField(to='appFitnes.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('alimentoID', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('porcion', models.IntegerField()),
                ('kcalorias', models.IntegerField()),
                ('usuario', models.ManyToManyField(to='appFitnes.usuarios')),
            ],
        ),
    ]
